GEMINI_API_KEYS = [
    "ADD_YOUR_GEMINI_API_KEY_HERE"
]

VIRUSTOTAL_API_KEY = "ADD_YOUR_VT_API_KEY"

WHATSAPP_TOKEN = "ADD_YOUR_WHATSAPP_TOKEN"

WHATSAPP_PHONE_ID = "ADD_PHONE_ID"

VERIFY_TOKEN = "ADD_VERIFY_TOKEN"